### ISSUE TITLE
About pretrained models

### ISSUE THREAD

**Issue by QT-Zhu** [zhou13/holicity#1]
Thank you and everyone involved for this significant work that fills a recent vacancy of datasets!

I would like to ask whether you will provide pretrained models whose results are illustrated in the paper in the future as a benchmark?

**Comment by zhou13** [comment]
We provide the pretrained MaskRCNN models at https://github.com/Delay-Xili/HoliCity-MaskRCNN, which performs the best according to our tests. For the other models, we currently have no plan to release them.
