### ISSUE TITLE
Generating new perspective viewpoints with normal maps

### ISSUE THREAD

**Issue by mattangus** [zhou13/holicity#10]
I would like to generate new perspective images (with random angles). Modifying `panorama2perspective.py` can accomplish this. However I would like to also generate the accompanying normal maps. Is there a way to do this?

**Comment by zhou13** [comment]
Unfortunately, this can be a little bit complex. I suppose you don't want to deal with rendering the 3D mesh yourself. Then what you can do is for pixel, you try to find an existing normal map that covers that pixel, and rotate the normal directly according to the view angle.

**Comment by mattangus** [comment]
Thanks for the reply! That's what I'm trying to do right now. Just trying to reverse the math in the vertex and fragment shader to compute the corresponding pixel location in the panorama.

**Comment by mattangus** [comment]
@zhou13 I think I have the math figured out! I'm having some issues with the calibration of the panos (i.e. `pano_yaw`, `tilt_pitch`, and `tilt_yaw`). They seem to be off in some panos (e.g. `rJBKAQke8TBO7YTQikgjlw.jpg` and `pu5rF1i4w2ZwbM9pKUi_Jg.jpg`). How are those calculated?

**Comment by mattangus** [comment]
Actually the problem is with the projection of points from a perspective image to the panorama. Currently I have this:

```python
def project_equirectangular(pt, input_size):
    pt = pt / np.linalg.norm(pt)
    theta = atan2(pt[1], pt[0])
    phi = asin(pt[2])
    
    pt_prime =  np.array([(theta + np.pi) / (2 * np.pi), (phi + np.pi / 2) / np.pi])
    pt_eq = pt_prime * input_size
    return pt[:2] / pt[2]

K = np.array([
        [254.73099999999394, 0, 512/2],
        [0, 254.73099999999394, 512/2],
        [0, 0, 1]
    ]) # camera matrix for the opengl camera. focal length is estimated, I couldn't find a way to analytically compute it and have images line up properly.
pixel = ... # a given pixel in the perspective image
yaw, pitch = ... # parsed from the image name i.e. <key>_<quality>_<yaw>_<pitch>_nrml.npz
ph = np.linalg.inv(K) @ np.concat([pixel, 1]) # pixel in homogeneous camera coords

R = (
    rotate(pano_yaw, axis)
    @ rotate(tilt_pitch, np.cross([np.cos(tilt_yaw), np.sin(tilt_yaw), 0], axis))
    @ lookat([0, 0, 0],
                    [np.cos(pitch) * np.cos(yaw), np.cos(pitch) * np.sin(yaw), np.sin(pitch)],
                    [0, 0, 1],)
    )[:3, :3].T # taken from panorama2perspective.py
pr = R @ ph # rotate pixel from perspective to pano reference frame
eq_pt = project_equirectangular(pr, (13312, 6656)) # this should be the corresponding pixel in the panorama
```

The issue I have is with the rotation `R`. It doesn't seem to map pixels properly (i.e. drawing `eq_pt` on the pano and `pixel` on the perspective image doesn't line up). I have tested the projection and it works with an R that I generate in different ways. But I'm struggling to align the pixels from the perspective images (rotation parsed from the filename) with the rotation matrix R.

**Comment by mattangus** [comment]
@zhou13 I have done some experiments. I have manually selected pixels in the panorama (`8heFyix0weuW7Kzd6A_BLg.jpg`) and a perspective image (`8heFyix0weuW7Kzd6A_BLg_LD_196_44_imag.jpg`) that match.
```python
    persp_points = np.array([
        [ 14, 410],
        [ 34, 375],
        [131, 296],
        [ 42, 200],
        [162,  65],
        [384, 478],
        [323, 319],
        [204, 279],
        [166, 330],
        [259, 302],])
    pano_points = np.array([
        [11747,  3004],
        [11750,  2821],
        [12086,  2215],
        [11168,  1885],
        [11029,   729],
        [  665,  3255],
        [  489,  2286],
        [12671,  1971],
        [12437,  2402],
        [13233,  2125],])
```
 Then backprojecting each set of pixels:
```python
    def backproject(p):
        p = p / [w, h] # normalize by image size
        theta = p[0] * 2 * np.pi - np.pi
        phi = p[1] * np.pi - np.pi / 2
        ray = np.array([
            np.cos(phi) * np.cos(theta),
            np.cos(phi) * np.sin(phi),
            np.sin(phi)])
        return ray / np.linalg.norm(ray)

    pano_rays = np.array([backproject(p) for p in pano_points])
    persp_rays = ((persp_points - 256)) / 256 # backproject pinhole
    persp_rays = np.concatenate([persp_rays, np.ones([persp_rays.shape[0], 1])], -1)
    pano_rays /= np.linalg.norm(pano_rays, axis=1)[:, None]
    persp_rays /= np.linalg.norm(persp_rays, axis=1)[:, None]
```

So now with these ray correspondences I compute a rigid transformation (described [here](http://nghiaho.com/?page_id=671) and code [here](https://github.com/nghiaho12/rigid_transform_3D/blob/master/rigid_transform_3D.py)) between these two sets of points. The only difference is that I set the centroids to `[0,0,0]` so that the rotation is just about the origin. The final rotation lines up well with a residual of `0.001`. Finally I convert the output rotation matrix to euler angles using [`scipy as_euler`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.as_euler.html#scipy.spatial.transform.Rotation.as_euler).

```python
R = rigid_transform_3D(pano_rays.T, persp_rays.T)
residual = np.sum((R @ pano_rays.T).T - B)
print(residual)
print(Rotation.from_matrix(R).as_euler("zyx", degrees=True))
```

The values I get are `[  92.68220638   -0.4724457  -132.83245119]`. My question is how does this relate to the `yaw=196, pitch=44,pano_yaw=-18.756548324008367, tilt_yaw=4.9089237447313225,tilt_pitch=1.206593359353629` values supplied by the dataset?

`yaw + pano_yaw - 90 = 88` is close to the 92 yaw from the rigid transformation, and `pitch - 180 = -136` is close to -132 pitch from the rigid transform. The difference in angle seems too large and is probably just a coincidence. Maybe if I incorporate the small `tilt_yaw` and `tilt_pitch` then these values will line up. I'm just not sure how to do that!

Decomposing the matrix from `panorama2perspective.py` in the same way gives vastly different numbers!

```python
    sind = lambda x: np.sin(np.radians(x))
    cosd = lambda x: np.cos(np.radians(x))
    other_rot = (
        rotate(data["pano_yaw"], [0, 0, 1])
        @ rotate(
            data["tilt_pitch"], np.cross([cosd(data["tilt_yaw"]), sind(data["tilt_yaw"]), 0], [0, 0, 1]),
        )
        @ lookat(
            [0, 0, 0],
            [cosd(pitch) * cosd(yaw), cosd(pitch) * sind(yaw), sind(pitch)],
            [0, 0, 1],
        )
    )[:3, :3]
    print(other_rot)
    print(Rotation.from_matrix(other_rot).as_euler("zyx", degrees=True))
```

The output of this is `[-134.28528133   35.27177415 -150.3281829 ]`. So that doesn't help...

I've been banging my head on the keyboard for a few days over this so any help is appreciated! Part of the confusion is definitely coming from the change in convention between OpenGL and OpenCV.

**Comment by mattangus** [comment]
Turns out to be just an axis convention problem 🤦 Sorry for the spam!

**Comment by zhou13** [comment]
No worries. Let me know if you have further questions.

**Comment by ShadowXZT** [comment]
> Turns out to be just an axis convention problem 🤦 Sorry for the spam!

Hi @mattangus, How did you solve this problem? I have tried your code and the result is different from yours :(.
