### ISSUE TITLE
AccuCities textured model coordinate frame

### ISSUE THREAD

**Issue by v-pnk** [zhou13/holicity#12]
Hello,
do you have also the transformation of the camera poses to the textured London model provided by AccuCities (https://www.accucities.com/product/tq3280-free-textured-3d-london-sample/)?

It seems to have different coordinate frame than the no-color CAD models.

Thanks in advance!

**Comment by zhou13** [comment]
I was not aware of the textured London model from AccuCities. It was published recently. The camera pose in this project should be consistent with the old no-color CAD models.

**Comment by v-pnk** [comment]
Thank you!

Closing the issue as my question was answered.
