### ISSUE TITLE
Dataset download link has been expired

### ISSUE THREAD

**Issue by YaoXingbo** [zhou13/holicity#18]
Hi, Professor ZHOU,
I’m a researcher at the Hong Kong University of Science and Technology. 

I am currently working on research related to 3D diffusion and am very interested in using the Holicity dataset. However, the download link on the Holicity dataset's website appears to be expired.

Could you please update the download link or provide an alternative method for accessing the dataset? This would be greatly beneficial for the progress of my research.

Thank you very much for your patience and assistance. I look forward to your response.

**Comment by zhou13** [comment]
Duplicated with #17.

**Comment by zhou13** [comment]
@YaoXingbo  I have updated the homepage of holicity. The data is hosted by huggingface now.
