### ISSUE TITLE
Erroneous plane instance data

### ISSUE THREAD

**Issue by mukulkhanna** [zhou13/holicity#6]
Thank you for your contributions.

I was playing around with the dataset, and found some anomalies in the plane instances and corresponding normal maps for several images. Here are the paths of the images I am referring to (with corresponding visualizations below) -

1. `2008-07/8heFyix0weuW7Kzd6A_BLg_LD_265_03_imag.jpg`
2. `2008-07/C8XvKma5K3Z1GmDYt-hoZg_LD_121_19_imag.jpg`
3. `2008-07/C8XvKma5K3Z1GmDYt-hoZg_LD_218_08_imag.jpg`
4. `2008-07/C8XvKma5K3Z1GmDYt-hoZg_LD_261_24_imag.jpg`

#### RGB images

1 |  2 | 3 | 4 |
:--:|:--:|:--:|:--:
![000005](https://user-images.githubusercontent.com/24846546/104157580-6d4ef380-5411-11eb-90e5-15a15587ae28.png) | ![000010](https://user-images.githubusercontent.com/24846546/104157586-6f18b700-5411-11eb-88a3-e2c8a26add14.png) | ![000012](https://user-images.githubusercontent.com/24846546/104157589-6fb14d80-5411-11eb-8d1f-bd3475c4152f.png) | ![000013](https://user-images.githubusercontent.com/24846546/104157591-7049e400-5411-11eb-8435-3c60d211bd1a.png)

#### Plane overlays

Below are the corresponding plane overlays generated using the `planes.py` code from the repository (after changing the input images)

1 |  2 | 3 | 4 |
:--:|:--:|:--:|:--:
![](https://user-images.githubusercontent.com/24846546/104157168-9fac2100-5410-11eb-8abe-4e43fb3b67ae.png)  |  ![](https://user-images.githubusercontent.com/24846546/104157185-a89cf280-5410-11eb-893d-1c0c79bb4b6f.png) | ![000012](https://user-images.githubusercontent.com/24846546/104157226-bce0ef80-5410-11eb-8aa4-4edfd86a82ff.png) | ![000013](https://user-images.githubusercontent.com/24846546/104157230-be121c80-5410-11eb-937b-a1088da0ff4d.png)

Is this expected? Could you suggest a way of dealing with this? Perhaps a cleaner subset of the dataset? Or anything I'm missing?

Thanks!

**Comment by zhou13** [comment]
Hi @mukulkhanna , thanks for being interested in our dataset. These are often caused by the remodeling of buildings and errors in the CAD models. Models that end with `_HD` have fewer problems like this. Internally we do have a list of cleaner subsets. However, we haven't found performance improvement by training on it so we think this shouldn't be a huge problem for normal estimation and plane segmentation.

**Comment by mukulkhanna** [comment]
Thanks @zhou13 !
