### ISSUE TITLE
test annotations error

### ISSUE THREAD

**Issue by AhmedAbdouz** [zhou13/holicity#8]
I have downloaded the data right now and when I checked the "**test-middlesplit.txt**" file I found there are some images don't have a plane annotations and gives me this error 
`Traceback (most recent call last):
  File "find_names.py", line 112, in <module>
    shutil.copyfile(str, f"new_split/annos_{split}/{name}")
  File "/home/aahmed/anaconda3/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'plane-v1/2012-05/8uwSwdotH2k87VYVkHYdDg_LD_011_42_plan.png'
`
I went to the plane folder and searched for the name "8uwSwdotH2k87VYVkHYdDg_LD" that is present in the error and I couldn't find the plane annotation for that image although the image was in the images folders.

**Comment by AhmedAbdouz** [comment]
how can I get a consistent split for training and testing? shouldn't the split files of your dataset for each image has their complete annotations from depth, normal, plane ..... wheater for train or test.

**Comment by zhou13** [comment]
The test splits were used in a competition and I haven't released their annotation. Please used `valid-middlesplit.txt` for now.

**Comment by AhmedAbdouz** [comment]
Thank you for your reply
